export enum AppPaths {
  FOUR_LAWS = '/4laws'
}

const FOUR_LAWS_ROOT = '/4laws';

const FOUR_LAWS_MAIN = FOUR_LAWS_ROOT + '/main';
const FOUR_LAWS_MAIN_TITLE = FOUR_LAWS_MAIN + '/0';
const FOUR_LAWS_MAIN_WRAPUP = FOUR_LAWS_MAIN + '/1';

const FOUR_LAWS_ONE = FOUR_LAWS_ROOT + '/one';
const FOUR_LAWS_ONE_TITLE = FOUR_LAWS_ONE + '/0';
const FOUR_LAWS_ONE_CONTENT_1 = FOUR_LAWS_ONE + '/1';
const FOUR_LAWS_ONE_CONTENT_2 = FOUR_LAWS_ONE + '/2';
const FOUR_LAWS_ONE_WRAPUP = FOUR_LAWS_ONE + '/3';

const FOUR_LAWS_TWO = FOUR_LAWS_ROOT + '/two';

const FOUR_LAWS_THREE = FOUR_LAWS_ROOT + '/three';

const FOUR_LAWS_FOUR = FOUR_LAWS_ROOT + '/four';

const FOUR_LAWS_PRAYER = FOUR_LAWS_ROOT + '/prayer';

export const FourLawsPaths = {
  ROOT: FOUR_LAWS_ROOT,
  MAIN: FOUR_LAWS_MAIN,
  MAIN_TITLE: FOUR_LAWS_MAIN_TITLE,
  MAIN_WRAPUP: FOUR_LAWS_MAIN_WRAPUP,
  LAW_ONE: FOUR_LAWS_ONE,
  LAW_ONE_TITLE: FOUR_LAWS_ONE_TITLE,
  LAW_ONE_1: FOUR_LAWS_ONE_CONTENT_1,
  LAW_ONE_2: FOUR_LAWS_ONE_CONTENT_2,
  LAW_ONE_WRAPUP: FOUR_LAWS_ONE_WRAPUP,
  LAW_TWO: FOUR_LAWS_TWO,
  LAW_THREE: FOUR_LAWS_THREE,
  LAW_FOUR: FOUR_LAWS_FOUR,
  PRAYER: FOUR_LAWS_PRAYER
  
};